version: '2'
services:
    mywebapp-app:
        image: mywebapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mywebapp-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mywebapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mywebapp-mongodb:
        extends:
            file: mongodb.yml
            service: mywebapp-mongodb
